version: '3'
services:
  # redis:
  #   image: "redis:alpine"
  postgres:
    image: "postgres:10"
    environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: testdb
    ports:
     - "5432:5432" 
  server:
    build:
      context: ./
      dockerfile: dev/Dockerfile
    ports:
     - "7000:7000"
    volumes:
     - ./:/srv
     - ./dev/.bash_history:/root/.ash_history
    depends_on:
      - postgres
      # - redis 
    environment:
     POSTGRES_HOST: postgres
     POSTGRES_PORT: 5432
     POSTGRES_USER: postgres
     PGPASSWORD: postgres
     POSTGRES_DB: testdb